# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: generate
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen  
    desc: "Generate binary code from Go-files"  
    cmds:  ## Тут описываем необходимые bash-команды
      - go build -o main.exe main.go task_1.go task_2.go task_3.go task_4.go task_5.go task_6.go task_7.go task_8.go
      - ./main.exe